const chalk = require('chalk');
 
console.log("")
console.log("")
console.log("")
console.log("")

 
console.log(chalk.blue("                      Arun                      "))
console.log(chalk.red("                   Arun  Arun "))
console.log(chalk.bold.yellow("                Arun       Arun"))
console.log(chalk.magenta("               Arun          Arun"))
console.log(chalk.cyan("             Arun              Arun      "))
console.log(chalk.bold.magenta("           Arun Arun Arun Arun ArunArun        "))
console.log(chalk.bold.red("         Arun                       Arun"))
console.log(chalk.red("       Arun                           Arun"))
console.log(chalk.red("     Arun                               Arun"))
console.log(chalk.red("   Arun                                   Arun"))
console.log(chalk.red(" Arun                                       Arun"))
console.log("")
console.log("")
console.log("")
console.log("")

console.log(chalk.blue.underline("Arun Arun Arun Arun Arun Arun Arun Arun Arun"))
console.log(chalk.red("ArunArun                           Arun Arun"))
console.log(chalk.magenta("ArunArun                           Arun Arun"))
console.log(chalk.bold.yellow("Arun Arun                          Arun Arun"))
console.log(chalk.cyan("Arun Arun Arun Arun Arun Arun Arun Arun Arun"))
console.log(chalk.bold.magenta("Arun Arun Arun Arun       "))
console.log(chalk.bold.red("Arun Arun         Arun"))
console.log(chalk.red("Arun Arun            Arun"))
console.log(chalk.red("Arun Arun                Arun"))
console.log(chalk.red("Arun Arun                    Arun"))
console.log(chalk.red("Arun Arun                        Arun"))
console.log(chalk.red("Arun Arun                           Arun"))
console.log(chalk.red("Arun Arun                               Arun"))

console.log("")
console.log("")
console.log("")
console.log("")

console.log(chalk.blue("Arun Arun                          Arun Arun"))
console.log(chalk.red("ArunArun                           Arun Arun"))
console.log(chalk.magenta("ArunArun                           Arun Arun"))
console.log(chalk.bold.yellow("Arun Arun                          Arun Arun"))
console.log(chalk.blue("Arun Arun                          Arun Arun"))
console.log(chalk.red("ArunArun                           Arun Arun"))
console.log(chalk.magenta("ArunArun                           Arun Arun"))
console.log(chalk.bold.yellow("Arun Arun                        Arun Arun"))
console.log(chalk.bold.yellow("Arun Arun                          Arun Arun"))
console.log(chalk.blue("Arun Arun                          Arun Arun"))
console.log(chalk.red.underline("ArunArun Arun Arun Arun Arun  Arun Arun Arun"))

console.log("")
console.log("")
console.log("")
console.log("")

console.log(chalk.blue("Arun Arun Arun                     Arun Arun"))
console.log(chalk.red("ArunArun      Arun                 Arun Arun"))
console.log(chalk.magenta("ArunArun         Arun              Arun Arun"))
console.log(chalk.bold.yellow("Arun Arun          Arun            Arun Arun"))
console.log(chalk.blue("Arun Arun            Arun          Arun Arun"))
console.log(chalk.red("ArunArun               Arun        Arun Arun"))
console.log(chalk.magenta("ArunArun                 Arun      Arun Arun"))
console.log(chalk.bold.yellow("Arun Arun                  Arun    Arun Arun"))
console.log(chalk.bold.yellow("Arun Arun                     Arun Arun Arun"))
console.log(chalk.blue("Arun Arun                         Arun Arun Arun"))


